stages:
  - deploy

.deploy_base:
  stage: deploy
  image: alpine:latest
  tags:
    - charch
  before_script:
    - apk add --no-cache openssh-client curl bind-tools busybox-extras
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp "$SSH_PRIVATE_KEY" ~/.ssh/deploy_key
    - chmod 600 ~/.ssh/deploy_key
    - ssh-add ~/.ssh/deploy_key
    - 'echo "Runner public IP: $(curl -s --connect-timeout 2 --max-time 5 https://ifconfig.me || true)"'
    - nslookup $DEPLOY_HOST || true
    - nc -vz -w 5 $DEPLOY_HOST 22 || true
  environment:
    name: development
    url: https://dev.lacos.uni-koeln.de

deploy_dev_full:
  extends: .deploy_base
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      changes:
        - "requirements/**/*"
        - "compose/**/*"
        - "**/migrations/**/*"
  script:
    - ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "cd /opt/lacos/lac-app && git pull origin dev && docker compose -f docker-compose.dev.yml --profile build run --rm --no-deps theme && docker compose -f docker-compose.dev.yml up -d --build django"

deploy_dev_fast:
  extends: .deploy_base
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      changes:
        - "requirements/**/*"
        - "compose/**/*"
        - "**/migrations/**/*"
      when: never
    - if: '$CI_COMMIT_BRANCH == "dev"'
  script:
    - ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "cd /opt/lacos/lac-app && git pull origin dev && docker compose -f docker-compose.dev.yml --profile build run --rm --no-deps theme && docker compose -f docker-compose.dev.yml restart django"
