volumes:
  lacos_local_postgres_data: {}
  lacos_local_postgres_data_backups: {}
  lacos_local_redis_data: {}
  minio_data: {}

networks:
  lacos_network_ws:
    driver: bridge

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
      target: web-run-stage
    image: lacos_local_django
    restart: unless-stopped
    depends_on:
      - postgres
      - minio
    volumes:
      - .:/app:z
      - ../lac-guidelines:/lac-guidelines:ro
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.storage
    environment:
      SAML_LOGIN_ENABLED: "true"
      SAML_DJANGO_USER_MAIN_ATTRIBUTE: "username"
      SAML_USE_NAME_ID_AS_USERNAME: "false"
      SAML_SP_BASE_URL: "http://localhost:8101"
      SAML_IDP_METADATA_LOCAL: "/app/shibboleth.xml"
    ports:
      - '127.0.0.1:8101:8000'
    command: /bin/bash -lc "python manage.py migrate && uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html' --no-access-log"
    networks:
      - lacos_network_ws

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: lacos_production_postgres
    volumes:
      - lacos_local_postgres_data:/var/lib/postgresql/data
      - lacos_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - lacos_network_ws

  minio:
    image: minio/minio
    ports:
      - "127.0.0.1:9100:9000"
      - "127.0.0.1:9101:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_API_ALLOW_CORS_ORIGIN: "*"
      MINIO_BROWSER_REDIRECT_URL: "http://localhost:9101"
      MINIO_DOMAIN_NAME: "localhost:9100"
      MINIO_LOGGER: "console"
      MINIO_LOGGER_LEVEL: "debug"
      MINIO_CORS_ALLOW_ORIGINS: "*"
      MINIO_CORS_ALLOW_METHODS: "GET,PUT,POST,DELETE,OPTIONS"
      MINIO_CORS_ALLOW_HEADERS: "*"
      MINIO_CORS_EXPOSE_HEADERS: "ETag"
      MINIO_CORS_MAX_AGE_SECONDS: "3600"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - lacos_network_ws


  redis:
    image: "redis:latest"
    volumes:
      - lacos_local_redis_data:/data
    ports:
      - "127.0.0.1:6381:6379"
    networks:
      - lacos_network_ws
    command: redis-server --appendonly yes

  huey:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
      target: worker-run-stage
    image: lacos_local_huey
    depends_on:
      - django
      - redis
    volumes:
      - .:/app:z
      - ../lac-guidelines:/lac-guidelines:ro
      - lacos_local_postgres_data_backups:/backups
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.storage
    environment:
      SAML_LOGIN_ENABLED: "true"
      SAML_DJANGO_USER_MAIN_ATTRIBUTE: "username"
      SAML_USE_NAME_ID_AS_USERNAME: "false"
      SAML_SP_BASE_URL: "http://localhost:8101"
      SAML_IDP_METADATA_LOCAL: "/app/shibboleth.xml"
    command: /bin/sh -c "python manage.py run_huey"
    networks:
      - lacos_network_ws

  node:
    image: node:latest
    depends_on:
      - django
    working_dir: /app/theme/static_src
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/app:z
    command: /bin/sh -c "npm install && npm run dev"
    tty: true
    networks:
      - lacos_network_ws
