# Generated by Django 5.0.12 on 2025-04-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundleobjectlanguage',
            name='bundle',
        ),
    ]
