# Generated by Django 5.0.12 on 2025-09-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='source_version',
            field=models.CharField(blank=True, help_text='BLAM schema version used during the latest import', max_length=20, null=True),
        ),
    ]
