# Generated by Django 5.0.12 on 2025-09-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0002_collection_source_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='import_bucket',
            field=models.CharField(blank=True, help_text='S3 bucket used when this bundle was imported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='import_object_key',
            field=models.TextField(blank=True, help_text='Original S3 object key used for the bundle import', null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='import_bucket',
            field=models.CharField(blank=True, help_text='S3 bucket used when this collection was imported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='import_object_key',
            field=models.TextField(blank=True, help_text='Original S3 object key used for the collection import', null=True),
        ),
    ]
