# Generated by Django 5.0.12 on 2025-04-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0002_remove_bundleobjectlanguage_bundle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bundlepublicationinfo',
            unique_together=set(),
        ),
    ]
