# Generated by Django 5.0.12 on 2025-10-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0003_bundle_import_bucket_bundle_import_object_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Projects associated with this bundle', related_name='bundles', to='blam.projectinfo'),
        ),
        migrations.AddField(
            model_name='collection',
            name='project_infos',
            field=models.ManyToManyField(blank=True, help_text='Projects associated with this collection', related_name='collections', to='blam.projectinfo'),
        ),
        migrations.AddField(
            model_name='funderinfo',
            name='funder_identifiers',
            field=models.ManyToManyField(blank=True, help_text='Identifiers for the funding organization', related_name='funder_infos', to='blam.funderidentifier'),
        ),
    ]
