# Generated by Django 5.0.12 on 2025-04-02 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0003_alter_bundlepublicationinfo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlestructuralinfo',
            name='resources',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structural_info', to='blam.bundleresources'),
        ),
    ]
