# Generated by Django 5.0.12 on 2026-01-12 10:44

import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0004_project_links_and_funder_identifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundleadditionalmetadatafile',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundleadministrativeinfo',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundlecontributor',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundlecreator',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundlegeneralinfo',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundlehasbundlemember',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundleheader',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundleidenticalresource',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundlekeyword',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundlelicense',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundlelocation',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundlemembers',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundleobjectlanguage',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundleobjectlanguagealternativename',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundleobjectlanguagelanguagefamily',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundleobjectlanguagetaxonomy',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundlepublicationinfo',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundleresources',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundlerightsholder',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundlerightsholderidentifier',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundletopic',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bundletopics',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionadditionalmetadatafile',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionadministrativeinfo',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectioncontributor',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectioncreator',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectiongeneralinfo',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionheader',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionidenticalresource',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionkeyword',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionlicense',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionlocation',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionobjectlanguage',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionobjectlanguagealternativename',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionobjectlanguagelanguagefamily',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionobjectlanguagetaxonomy',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionpublicationinfo',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionrightsholder',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionrightsholderidentifier',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='funderidentifier',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='funderinfo',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediaresource',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otherresource',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='writtenresource',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='writtenresourceannotation',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
