# Generated by Django 5.0.12 on 2025-04-04 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0004_bundlestructuralinfo_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlestructuralinfo',
            name='resources',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structural_info', to='blam.bundleresources'),
        ),
    ]
