# Generated by Django 5.0.12 on 2026-01-28 19:25

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0005_alter_bundle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='bundle',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='bundle_search_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='collection_search_gin_idx'),
        ),
    ]
