# Generated by Django 5.0.12 on 2026-01-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0006_add_search_vector_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlecreator',
            name='order',
            field=models.IntegerField(blank=True, help_text='Order in citation list', null=True),
        ),
        migrations.AddField(
            model_name='collectioncreator',
            name='order',
            field=models.IntegerField(blank=True, help_text='Order in citation list', null=True),
        ),
    ]
