# Generated by Django 5.0.12 on 2026-02-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0007_add_order_to_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionheader',
            name='md_license',
            field=models.CharField(blank=True, help_text='Metadata document license (MDLicense value)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionheader',
            name='md_license_uri',
            field=models.URLField(blank=True, help_text='Metadata document license URI (MDLicense URI)', null=True),
        ),
    ]
