# Generated by Django 5.0.12 on 2026-02-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0008_collectionheader_md_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundleobjectlanguage',
            name='glottolog_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bundleobjectlanguage',
            name='iso_639_3_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='collectionobjectlanguage',
            name='glottolog_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='collectionobjectlanguage',
            name='iso_639_3_code',
            field=models.CharField(max_length=3),
        ),
    ]
