# Generated by Django 5.0.12 on 2026-02-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0014_add_md_license_to_bundle_header'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bundle',
            name='bnd_ident_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='bundleadministrativeinfo',
            name='bndl_admin_access_idx',
        ),
        migrations.RemoveIndex(
            model_name='bundlegeneralinfo',
            name='bnd_title_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='bundlekeyword',
            name='bndl_keyword_value_idx',
        ),
        migrations.RemoveIndex(
            model_name='bundlelicense',
            name='bndl_license_access_idx',
        ),
        migrations.RemoveIndex(
            model_name='bundlelocation',
            name='bndl_loc_country_facet_idx',
        ),
        migrations.RemoveIndex(
            model_name='bundlelocation',
            name='bndl_loc_region_facet_idx',
        ),
        migrations.RemoveIndex(
            model_name='bundleobjectlanguage',
            name='bndl_lang_iso639_idx',
        ),
        migrations.RemoveIndex(
            model_name='bundlepublicationinfo',
            name='bndl_pub_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='bundlepublicationinfo',
            name='bndl_pub_provider_idx',
        ),
        migrations.RemoveIndex(
            model_name='bundletopic',
            name='bndl_topic_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='col_ident_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='collectionadministrativeinfo',
            name='coll_admin_access_idx',
        ),
        migrations.RemoveIndex(
            model_name='collectiongeneralinfo',
            name='col_title_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='collectionkeyword',
            name='coll_keyword_value_idx',
        ),
        migrations.RemoveIndex(
            model_name='collectionlicense',
            name='coll_license_access_idx',
        ),
        migrations.RemoveIndex(
            model_name='collectionlocation',
            name='coll_loc_country_facet_idx',
        ),
        migrations.RemoveIndex(
            model_name='collectionlocation',
            name='coll_loc_region_facet_idx',
        ),
        migrations.RemoveIndex(
            model_name='collectionobjectlanguage',
            name='coll_lang_iso639_idx',
        ),
        migrations.RemoveIndex(
            model_name='collectionpublicationinfo',
            name='coll_pub_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='collectionpublicationinfo',
            name='coll_pub_provider_idx',
        ),
    ]
