# Generated by Django 5.0.12 on 2026-02-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0015_remove_bundle_bnd_ident_trgm_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundletopics',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='bundlestructuralinfo',
            name='bundle_topics',
        ),
        migrations.RemoveField(
            model_name='bundletopics',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='bundletopics',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bundletopics',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='BundleTopic',
        ),
        migrations.DeleteModel(
            name='BundleTopics',
        ),
    ]
