# Generated by Django 5.2.12 on 2026-03-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0017_creator_order_to_through_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='import_etag',
            field=models.CharField(blank=True, help_text='S3 ETag from last successful reindex', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='import_etag',
            field=models.CharField(blank=True, help_text='S3 ETag from last successful reindex', max_length=255, null=True),
        ),
    ]
