# Generated by Django 5.2.13 on 2026-06-17 07:00

import django.db.models.deletion
import lacos.blam.models.base_model
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blam', '0018_add_import_etag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionMember',
            fields=[
                ('id', models.UUIDField(default=lacos.blam.models.base_model.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier_value', models.CharField(help_text='Declared member identifier (e.g. a handle or DOI).', max_length=255)),
                ('identifier_type', models.CharField(blank=True, help_text='Identifier type as declared in the BLAM (e.g. Handle, DOI).', max_length=20)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('structural_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='blam.collectionstructuralinfo')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collection Member',
                'verbose_name_plural': 'Collection Members',
                'constraints': [models.UniqueConstraint(fields=('structural_info', 'identifier_value'), name='unique_collection_member_identifier')],
            },
        ),
    ]
