# Generated by Django 5.0.12 on 2025-04-01 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='initialized', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Session',
                'verbose_name_plural': 'Upload Sessions',
            },
        ),
        migrations.CreateModel(
            name='S3FileObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('original_path', models.CharField(blank=True, max_length=1024)),
                ('s3_key', models.CharField(max_length=1024)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage.uploadsession')),
            ],
            options={
                'verbose_name': 'S3 File Object',
                'verbose_name_plural': 'S3 File Objects',
            },
        ),
        migrations.CreateModel(
            name='ACLPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the object')),
                ('ACL_file_bucket', models.CharField(blank=True, help_text='S3 bucket containing the ACL file', max_length=255, null=True)),
                ('ACL_file_key', models.CharField(blank=True, help_text='S3 key for the ACL file', max_length=1024, null=True)),
                ('permissions_data', models.JSONField(blank=True, help_text='Parsed ACL permissions data', null=True)),
                ('last_synced', models.DateTimeField(blank=True, help_text='When the permissions were last synced from S3', null=True)),
                ('content_type', models.ForeignKey(help_text='Type of the object (Collection or Bundle)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'ACL Permissions',
                'verbose_name_plural': 'ACL Permissions',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='storage_acl_content_80204b_idx')],
            },
        ),
        migrations.CreateModel(
            name='S3ResourceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_pid', models.URLField(blank=True, help_text='PID/Handle that uniquely identifies the resource (optional)', null=True, unique=True)),
                ('s3_bucket', models.CharField(help_text='S3 bucket name where the resource is stored', max_length=255)),
                ('s3_key', models.CharField(help_text='S3 object key for the resource', max_length=1024)),
                ('size_bytes', models.BigIntegerField(blank=True, help_text='Size of the resource in bytes', null=True)),
                ('object_id', models.CharField(help_text='UUID or ID of the resource object', max_length=36)),
                ('content_type', models.ForeignKey(help_text='Type of the resource', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'S3 Resource Location',
                'verbose_name_plural': 'S3 Resource Locations',
                'indexes': [models.Index(fields=['resource_pid'], name='storage_s3r_resourc_21badb_idx'), models.Index(fields=['content_type', 'object_id'], name='storage_s3r_content_47d3dd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['user', 'status'], name='storage_upl_user_id_0374e7_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['created_at'], name='storage_upl_created_8d2374_idx'),
        ),
        migrations.AddIndex(
            model_name='s3fileobject',
            index=models.Index(fields=['session', 'status'], name='storage_s3f_session_fe5e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='s3fileobject',
            index=models.Index(fields=['s3_key'], name='storage_s3f_s3_key_417986_idx'),
        ),
    ]
