# Generated by Django 5.0.12 on 2025-10-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_backgroundtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aclpermissions',
            name='object_id',
            field=models.CharField(help_text='ID of the object', max_length=36),
        ),
    ]
