# Generated by Django 5.0.12 on 2025-10-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_aclpermissions_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aclpermissions',
            name='access_level',
            field=models.CharField(choices=[('embargo', 'Embargo'), ('private', 'Private'), ('protected', 'Protected'), ('public', 'Public')], default='embargo', help_text='Normalised access level inferred from the ACL entries', max_length=20),
        ),
        migrations.AddField(
            model_name='aclpermissions',
            name='read_agents',
            field=models.JSONField(blank=True, help_text='List of agent URIs or classes that have read access', null=True),
        ),
    ]
