# Generated by Django 5.0.12 on 2026-01-12 10:44

import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_s3resourcelocation_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtask',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='s3fileobject',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
