# Generated by Django 5.0.12 on 2026-01-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_backgroundtask_id_alter_s3fileobject_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
