# Generated by Django 5.0.12 on 2026-01-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_aclpermissions_access_levels_academic'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
