# Generated by Django 5.0.12 on 2026-01-26 13:06

from django.db import migrations, models


def backfill_bucket_name(apps, schema_editor):
    """Backfill bucket_name from session.bucket_name for existing records."""
    S3FileObject = apps.get_model('storage', 'S3FileObject')
    for file_obj in S3FileObject.objects.select_related('session').filter(bucket_name=''):
        if file_obj.session and file_obj.session.bucket_name:
            file_obj.bucket_name = file_obj.session.bucket_name
            file_obj.save(update_fields=['bucket_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_aclpermissions_access_levels_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3fileobject',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(backfill_bucket_name, migrations.RunPython.noop),
    ]
