# Generated by Django 5.0.12 on 2026-02-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('storage', '0014_add_bucket_name_to_s3fileobject'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aclpermissions',
            index=models.Index(fields=['content_type', 'object_id', 'access_level'], name='acl_ct_obj_level_idx'),
        ),
    ]
