# Generated by Django 5.0.12 on 2026-02-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_add_acl_access_level_covering_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtask',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20),
        ),
    ]
