# Generated by Django 5.2.12 on 2026-04-14 07:00

import lacos.blam.models.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_add_cancelled_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivativeStatus',
            fields=[
                ('id', models.UUIDField(default=lacos.blam.models.base_model.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket_name', models.CharField(max_length=255)),
                ('source_s3_key', models.CharField(max_length=1024)),
                ('source_etag', models.CharField(blank=True, max_length=255)),
                ('peaks_exists', models.BooleanField(default=False)),
                ('spectrogram_exists', models.BooleanField(default=False)),
                ('pitch_exists', models.BooleanField(default=False)),
                ('last_checked_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Derivative Status',
                'verbose_name_plural': 'Derivative Statuses',
                'indexes': [models.Index(fields=['bucket_name', 'peaks_exists'], name='storage_der_bucket__74a018_idx')],
                'constraints': [models.UniqueConstraint(fields=('bucket_name', 'source_s3_key'), name='unique_bucket_source_key')],
            },
        ),
    ]
