from django.urls import path

from .views.admin_views import (
    ArchivistDashboardView,
    ArchivistMetadataPanelView,
    DatabaseCleanupView,
    DatabaseDeleteAllView,
    DatabaseDeleteCollectionsView,
    DatabaseDeleteBundlesView,
    DatabaseDeleteConfirmView,
    DatabaseDeleteCollectionsConfirmView,
    DatabaseDeleteBundlesConfirmView
)
from .views.crud import delete_blam_model
from .views.export import CollectionJsonLdExportView
from .views.metadata import (
    CollectionListView,
    CollectionCreateView,
    CollectionOverviewView,
    CollectionHeaderView,
    CollectionGeneralInfoView,
    CollectionPublicationInfoView,
    CollectionAdministrativeInfoView,
    CollectionStructuralInfoView,
    CollectionProjectInfoView,
    BundleListView,
    BundleCreateView,
    BundleOverviewView,
    BundleHeaderView,
    BundleGeneralInfoView,
    BundlePublicationInfoView,
    BundleAdministrativeInfoView,
    BundleStructuralInfoView,
    BundleMembersView,
    BundleResourcesView,
    BundleProjectsView,
    ReferenceListView,
    ReferenceEditView,
    ReferenceDeleteView,
    CollectionPublicationReferencePanelView,
    CollectionPublicationReferenceEditView,
    CollectionPublicationReferenceRemoveView,
    BundlePublicationReferencePanelView,
    BundlePublicationReferenceEditView,
    BundlePublicationReferenceRemoveView,
    CollectionGeneralReferencePanelView,
    CollectionGeneralReferenceEditView,
    CollectionGeneralReferenceRemoveView,
    BundleGeneralReferencePanelView,
    BundleGeneralReferenceEditView,
    BundleGeneralReferenceRemoveView,
    CollectionObjectLanguageAltNamePanelView,
    CollectionObjectLanguageAltNameEditView,
    CollectionObjectLanguageAltNameRemoveView,
    CollectionObjectLanguageFamilyPanelView,
    CollectionObjectLanguageFamilyEditView,
    CollectionObjectLanguageFamilyRemoveView,
    BundleObjectLanguageAltNamePanelView,
    BundleObjectLanguageAltNameEditView,
    BundleObjectLanguageAltNameRemoveView,
    BundleObjectLanguageFamilyPanelView,
    BundleObjectLanguageFamilyEditView,
    BundleObjectLanguageFamilyRemoveView,
    CollectionAdministrativeReferencePanelView,
    CollectionAdministrativeReferenceEditView,
    CollectionAdministrativeReferenceRemoveView,
    BundleAdministrativeReferencePanelView,
    BundleAdministrativeReferenceEditView,
    BundleAdministrativeReferenceRemoveView,
    CollectionRightsHolderIdentifierPanelView,
    CollectionRightsHolderIdentifierEditView,
    CollectionRightsHolderIdentifierRemoveView,
    BundleRightsHolderIdentifierPanelView,
    BundleRightsHolderIdentifierEditView,
    BundleRightsHolderIdentifierRemoveView,
    CollectionStructuralReferencePanelView,
    CollectionStructuralReferenceEditView,
    CollectionStructuralReferenceRemoveView,
    BundleStructuralReferencePanelView,
    BundleStructuralReferenceEditView,
    BundleStructuralReferenceRemoveView,
    BundleResourcesReferencePanelView,
    BundleResourcesReferenceEditView,
    BundleResourcesReferenceRemoveView,
    WrittenResourceAnnotationPanelView,
    WrittenResourceAnnotationEditView,
    WrittenResourceAnnotationRemoveView,
    CollectionProjectReferencePanelView,
    CollectionProjectReferenceEditView,
    CollectionProjectReferenceRemoveView,
    BundleProjectReferencePanelView,
    BundleProjectReferenceEditView,
    BundleProjectReferenceRemoveView,
    ProjectFunderReferencePanelView,
    ProjectFunderReferenceEditView,
    ProjectFunderReferenceRemoveView,
    FunderIdentifierPanelView,
    FunderIdentifierEditView,
    FunderIdentifierRemoveView,
)

app_name = "blam"

# Admin/archivist routes
urlpatterns = [
    # Dashboard
    path('dashboard/archivist/', ArchivistDashboardView.as_view(), name='blam_archivist_dashboard'),
    path('dashboard/archivist/metadata-panel/', ArchivistMetadataPanelView.as_view(), name='blam_metadata_panel'),
    
    # Database operations
    path('admin/cleanup/', DatabaseCleanupView.as_view(), name='database_cleanup'),
    path('admin/delete-all/', DatabaseDeleteAllView.as_view(), name='database_delete_all'),
    path('admin/delete-all/confirm/', DatabaseDeleteConfirmView.as_view(), name='database_delete_all_confirm'),
    path('admin/delete-collections/', DatabaseDeleteCollectionsView.as_view(), name='database_delete_collections'),
    path('admin/delete-collections/confirm/', DatabaseDeleteCollectionsConfirmView.as_view(), name='database_delete_collections_confirm'),
    path('admin/delete-bundles/', DatabaseDeleteBundlesView.as_view(), name='database_delete_bundles'),
    path('admin/delete-bundles/confirm/', DatabaseDeleteBundlesConfirmView.as_view(), name='database_delete_bundles_confirm'),
    
    # API endpoints for file browser integration
    path('delete-model/<str:model_type>/<uuid:object_id>/', delete_blam_model, name='delete_model'),

    # Metadata CRUD
    path('metadata/collections/', CollectionListView.as_view(), name='collection_metadata_list'),
    path('metadata/collections/new/', CollectionCreateView.as_view(), name='collection_metadata_create'),
    path('metadata/collections/<uuid:collection_id>/', CollectionOverviewView.as_view(), name='collection_metadata_overview'),
    path('metadata/collections/<uuid:collection_id>/export/jsonld/', CollectionJsonLdExportView.as_view(), name='collection_export_jsonld'),
    path('metadata/collections/<uuid:collection_id>/header/', CollectionHeaderView.as_view(), name='collection_metadata_header'),
    path('metadata/collections/<uuid:collection_id>/general/', CollectionGeneralInfoView.as_view(), name='collection_metadata_general'),
    path(
        'metadata/collections/<uuid:collection_id>/general/references/<slug:reference_slug>/',
        CollectionGeneralReferencePanelView.as_view(),
        name='collection_general_reference_panel',
    ),
    path(
        'metadata/collections/<uuid:collection_id>/general/references/<slug:reference_slug>/<uuid:object_id>/',
        CollectionGeneralReferenceEditView.as_view(),
        name='collection_general_reference_edit',
    ),
    path(
        'metadata/collections/<uuid:collection_id>/general/references/<slug:reference_slug>/<uuid:object_id>/remove/',
        CollectionGeneralReferenceRemoveView.as_view(),
        name='collection_general_reference_remove',
    ),
    path(
        'metadata/collections/object-languages/<uuid:object_language_id>/alt-names/<slug:reference_slug>/',
        CollectionObjectLanguageAltNamePanelView.as_view(),
        name='collection_object_language_alt_names_panel',
    ),
    path(
        'metadata/collections/object-languages/<uuid:object_language_id>/alt-names/<slug:reference_slug>/<uuid:object_id>/',
        CollectionObjectLanguageAltNameEditView.as_view(),
        name='collection_object_language_alt_names_edit',
    ),
    path(
        'metadata/collections/object-languages/<uuid:object_language_id>/alt-names/<slug:reference_slug>/<uuid:object_id>/remove/',
        CollectionObjectLanguageAltNameRemoveView.as_view(),
        name='collection_object_language_alt_names_remove',
    ),
    path(
        'metadata/collections/object-languages/<uuid:object_language_id>/families/<slug:reference_slug>/',
        CollectionObjectLanguageFamilyPanelView.as_view(),
        name='collection_object_language_families_panel',
    ),
    path(
        'metadata/collections/object-languages/<uuid:object_language_id>/families/<slug:reference_slug>/<uuid:object_id>/',
        CollectionObjectLanguageFamilyEditView.as_view(),
        name='collection_object_language_families_edit',
    ),
    path(
        'metadata/collections/object-languages/<uuid:object_language_id>/families/<slug:reference_slug>/<uuid:object_id>/remove/',
        CollectionObjectLanguageFamilyRemoveView.as_view(),
        name='collection_object_language_families_remove',
    ),
    path('metadata/collections/<uuid:collection_id>/publication/', CollectionPublicationInfoView.as_view(), name='collection_metadata_publication'),
    path(
        'metadata/collections/<uuid:collection_id>/publication/references/<slug:reference_slug>/',
        CollectionPublicationReferencePanelView.as_view(),
        name='collection_publication_reference_panel',
    ),
    path(
        'metadata/collections/<uuid:collection_id>/publication/references/<slug:reference_slug>/<uuid:object_id>/',
        CollectionPublicationReferenceEditView.as_view(),
        name='collection_publication_reference_edit',
    ),
    path(
        'metadata/collections/<uuid:collection_id>/publication/references/<slug:reference_slug>/<uuid:object_id>/remove/',
        CollectionPublicationReferenceRemoveView.as_view(),
        name='collection_publication_reference_remove',
    ),
    path('metadata/collections/<uuid:collection_id>/administrative/', CollectionAdministrativeInfoView.as_view(), name='collection_metadata_administrative'),
    path(
        'metadata/collections/<uuid:collection_id>/administrative/references/<slug:reference_slug>/',
        CollectionAdministrativeReferencePanelView.as_view(),
        name='collection_administrative_reference_panel',
    ),
    path(
        'metadata/collections/<uuid:collection_id>/administrative/references/<slug:reference_slug>/<uuid:object_id>/',
        CollectionAdministrativeReferenceEditView.as_view(),
        name='collection_administrative_reference_edit',
    ),
    path(
        'metadata/collections/<uuid:collection_id>/administrative/references/<slug:reference_slug>/<uuid:object_id>/remove/',
        CollectionAdministrativeReferenceRemoveView.as_view(),
        name='collection_administrative_reference_remove',
    ),
    path(
        'metadata/collections/rights-holders/<uuid:rights_holder_id>/identifiers/<slug:reference_slug>/',
        CollectionRightsHolderIdentifierPanelView.as_view(),
        name='collection_rights_holder_identifiers_panel',
    ),
    path(
        'metadata/collections/rights-holders/<uuid:rights_holder_id>/identifiers/<slug:reference_slug>/<uuid:object_id>/',
        CollectionRightsHolderIdentifierEditView.as_view(),
        name='collection_rights_holder_identifiers_edit',
    ),
    path(
        'metadata/collections/rights-holders/<uuid:rights_holder_id>/identifiers/<slug:reference_slug>/<uuid:object_id>/remove/',
        CollectionRightsHolderIdentifierRemoveView.as_view(),
        name='collection_rights_holder_identifiers_remove',
    ),
    path('metadata/collections/<uuid:collection_id>/structural/', CollectionStructuralInfoView.as_view(), name='collection_metadata_structural'),
    path(
        'metadata/collections/<uuid:collection_id>/structural/references/<slug:reference_slug>/',
        CollectionStructuralReferencePanelView.as_view(),
        name='collection_structural_reference_panel',
    ),
    path(
        'metadata/collections/<uuid:collection_id>/structural/references/<slug:reference_slug>/<uuid:object_id>/',
        CollectionStructuralReferenceEditView.as_view(),
        name='collection_structural_reference_edit',
    ),
    path(
        'metadata/collections/<uuid:collection_id>/structural/references/<slug:reference_slug>/<uuid:object_id>/remove/',
        CollectionStructuralReferenceRemoveView.as_view(),
        name='collection_structural_reference_remove',
    ),
    path('metadata/collections/<uuid:collection_id>/projects/', CollectionProjectInfoView.as_view(), name='collection_metadata_projects'),
    path(
        'metadata/collections/<uuid:collection_id>/projects/references/<slug:reference_slug>/',
        CollectionProjectReferencePanelView.as_view(),
        name='collection_projects_reference_panel',
    ),
    path(
        'metadata/collections/<uuid:collection_id>/projects/references/<slug:reference_slug>/<uuid:object_id>/',
        CollectionProjectReferenceEditView.as_view(),
        name='collection_projects_reference_edit',
    ),
    path(
        'metadata/collections/<uuid:collection_id>/projects/references/<slug:reference_slug>/<uuid:object_id>/remove/',
        CollectionProjectReferenceRemoveView.as_view(),
        name='collection_projects_reference_remove',
    ),

    path('metadata/bundles/', BundleListView.as_view(), name='bundle_metadata_list'),
    path('metadata/bundles/new/', BundleCreateView.as_view(), name='bundle_metadata_create'),
    path('metadata/bundles/<uuid:bundle_id>/', BundleOverviewView.as_view(), name='bundle_metadata_overview'),
    path('metadata/bundles/<uuid:bundle_id>/header/', BundleHeaderView.as_view(), name='bundle_metadata_header'),
    path('metadata/bundles/<uuid:bundle_id>/general/', BundleGeneralInfoView.as_view(), name='bundle_metadata_general'),
    path(
        'metadata/bundles/<uuid:bundle_id>/general/references/<slug:reference_slug>/',
        BundleGeneralReferencePanelView.as_view(),
        name='bundle_general_reference_panel',
    ),
    path(
        'metadata/bundles/<uuid:bundle_id>/general/references/<slug:reference_slug>/<uuid:object_id>/',
        BundleGeneralReferenceEditView.as_view(),
        name='bundle_general_reference_edit',
    ),
    path(
        'metadata/bundles/<uuid:bundle_id>/general/references/<slug:reference_slug>/<uuid:object_id>/remove/',
        BundleGeneralReferenceRemoveView.as_view(),
        name='bundle_general_reference_remove',
    ),
    path(
        'metadata/bundles/object-languages/<uuid:object_language_id>/alt-names/<slug:reference_slug>/',
        BundleObjectLanguageAltNamePanelView.as_view(),
        name='bundle_object_language_alt_names_panel',
    ),
    path(
        'metadata/bundles/object-languages/<uuid:object_language_id>/alt-names/<slug:reference_slug>/<uuid:object_id>/',
        BundleObjectLanguageAltNameEditView.as_view(),
        name='bundle_object_language_alt_names_edit',
    ),
    path(
        'metadata/bundles/object-languages/<uuid:object_language_id>/alt-names/<slug:reference_slug>/<uuid:object_id>/remove/',
        BundleObjectLanguageAltNameRemoveView.as_view(),
        name='bundle_object_language_alt_names_remove',
    ),
    path(
        'metadata/bundles/object-languages/<uuid:object_language_id>/families/<slug:reference_slug>/',
        BundleObjectLanguageFamilyPanelView.as_view(),
        name='bundle_object_language_families_panel',
    ),
    path(
        'metadata/bundles/object-languages/<uuid:object_language_id>/families/<slug:reference_slug>/<uuid:object_id>/',
        BundleObjectLanguageFamilyEditView.as_view(),
        name='bundle_object_language_families_edit',
    ),
    path(
        'metadata/bundles/object-languages/<uuid:object_language_id>/families/<slug:reference_slug>/<uuid:object_id>/remove/',
        BundleObjectLanguageFamilyRemoveView.as_view(),
        name='bundle_object_language_families_remove',
    ),
    path('metadata/bundles/<uuid:bundle_id>/publication/', BundlePublicationInfoView.as_view(), name='bundle_metadata_publication'),
    path(
        'metadata/bundles/<uuid:bundle_id>/publication/references/<slug:reference_slug>/',
        BundlePublicationReferencePanelView.as_view(),
        name='bundle_publication_reference_panel',
    ),
    path(
        'metadata/bundles/<uuid:bundle_id>/publication/references/<slug:reference_slug>/<uuid:object_id>/',
        BundlePublicationReferenceEditView.as_view(),
        name='bundle_publication_reference_edit',
    ),
    path(
        'metadata/bundles/<uuid:bundle_id>/publication/references/<slug:reference_slug>/<uuid:object_id>/remove/',
        BundlePublicationReferenceRemoveView.as_view(),
        name='bundle_publication_reference_remove',
    ),
    path('metadata/bundles/<uuid:bundle_id>/administrative/', BundleAdministrativeInfoView.as_view(), name='bundle_metadata_administrative'),
    path(
        'metadata/bundles/<uuid:bundle_id>/administrative/references/<slug:reference_slug>/',
        BundleAdministrativeReferencePanelView.as_view(),
        name='bundle_administrative_reference_panel',
    ),
    path(
        'metadata/bundles/<uuid:bundle_id>/administrative/references/<slug:reference_slug>/<uuid:object_id>/',
        BundleAdministrativeReferenceEditView.as_view(),
        name='bundle_administrative_reference_edit',
    ),
    path(
        'metadata/bundles/<uuid:bundle_id>/administrative/references/<slug:reference_slug>/<uuid:object_id>/remove/',
        BundleAdministrativeReferenceRemoveView.as_view(),
        name='bundle_administrative_reference_remove',
    ),
    path(
        'metadata/bundles/rights-holders/<uuid:rights_holder_id>/identifiers/<slug:reference_slug>/',
        BundleRightsHolderIdentifierPanelView.as_view(),
        name='bundle_rights_holder_identifiers_panel',
    ),
    path(
        'metadata/bundles/rights-holders/<uuid:rights_holder_id>/identifiers/<slug:reference_slug>/<uuid:object_id>/',
        BundleRightsHolderIdentifierEditView.as_view(),
        name='bundle_rights_holder_identifiers_edit',
    ),
    path(
        'metadata/bundles/rights-holders/<uuid:rights_holder_id>/identifiers/<slug:reference_slug>/<uuid:object_id>/remove/',
        BundleRightsHolderIdentifierRemoveView.as_view(),
        name='bundle_rights_holder_identifiers_remove',
    ),
    path('metadata/bundles/<uuid:bundle_id>/structural/', BundleStructuralInfoView.as_view(), name='bundle_metadata_structural'),
    path(
        'metadata/bundles/<uuid:bundle_id>/structural/references/<slug:reference_slug>/',
        BundleStructuralReferencePanelView.as_view(),
        name='bundle_structural_reference_panel',
    ),
    path(
        'metadata/bundles/<uuid:bundle_id>/structural/references/<slug:reference_slug>/<uuid:object_id>/',
        BundleStructuralReferenceEditView.as_view(),
        name='bundle_structural_reference_edit',
    ),
    path(
        'metadata/bundles/<uuid:bundle_id>/structural/references/<slug:reference_slug>/<uuid:object_id>/remove/',
        BundleStructuralReferenceRemoveView.as_view(),
        name='bundle_structural_reference_remove',
    ),
    path('metadata/bundles/<uuid:bundle_id>/members/', BundleMembersView.as_view(), name='bundle_metadata_members'),
    path('metadata/bundles/<uuid:bundle_id>/resources/', BundleResourcesView.as_view(), name='bundle_metadata_resources'),
    path(
        'metadata/bundles/<uuid:bundle_id>/resources/references/<slug:reference_slug>/',
        BundleResourcesReferencePanelView.as_view(),
        name='bundle_resources_reference_panel',
    ),
    path(
        'metadata/bundles/<uuid:bundle_id>/resources/references/<slug:reference_slug>/<uuid:object_id>/',
        BundleResourcesReferenceEditView.as_view(),
        name='bundle_resources_reference_edit',
    ),
    path(
        'metadata/bundles/<uuid:bundle_id>/resources/references/<slug:reference_slug>/<uuid:object_id>/remove/',
        BundleResourcesReferenceRemoveView.as_view(),
        name='bundle_resources_reference_remove',
    ),
    path(
        'metadata/bundles/written-resources/<uuid:written_resource_id>/annotations/<slug:reference_slug>/',
        WrittenResourceAnnotationPanelView.as_view(),
        name='written_resource_annotations_panel',
    ),
    path(
        'metadata/bundles/written-resources/<uuid:written_resource_id>/annotations/<slug:reference_slug>/<uuid:object_id>/',
        WrittenResourceAnnotationEditView.as_view(),
        name='written_resource_annotations_edit',
    ),
    path(
        'metadata/bundles/written-resources/<uuid:written_resource_id>/annotations/<slug:reference_slug>/<uuid:object_id>/remove/',
        WrittenResourceAnnotationRemoveView.as_view(),
        name='written_resource_annotations_remove',
    ),
    path('metadata/bundles/<uuid:bundle_id>/projects/', BundleProjectsView.as_view(), name='bundle_metadata_projects'),
    path(
        'metadata/bundles/<uuid:bundle_id>/projects/references/<slug:reference_slug>/',
        BundleProjectReferencePanelView.as_view(),
        name='bundle_projects_reference_panel',
    ),
    path(
        'metadata/bundles/<uuid:bundle_id>/projects/references/<slug:reference_slug>/<uuid:object_id>/',
        BundleProjectReferenceEditView.as_view(),
        name='bundle_projects_reference_edit',
    ),
    path(
        'metadata/bundles/<uuid:bundle_id>/projects/references/<slug:reference_slug>/<uuid:object_id>/remove/',
        BundleProjectReferenceRemoveView.as_view(),
        name='bundle_projects_reference_remove',
    ),

    path(
        'metadata/projects/<uuid:project_id>/funders/<slug:reference_slug>/',
        ProjectFunderReferencePanelView.as_view(),
        name='project_funders_panel',
    ),
    path(
        'metadata/projects/<uuid:project_id>/funders/<slug:reference_slug>/<uuid:object_id>/',
        ProjectFunderReferenceEditView.as_view(),
        name='project_funders_edit',
    ),
    path(
        'metadata/projects/<uuid:project_id>/funders/<slug:reference_slug>/<uuid:object_id>/remove/',
        ProjectFunderReferenceRemoveView.as_view(),
        name='project_funders_remove',
    ),
    path(
        'metadata/funders/<uuid:funder_id>/identifiers/<slug:reference_slug>/',
        FunderIdentifierPanelView.as_view(),
        name='funder_identifiers_panel',
    ),
    path(
        'metadata/funders/<uuid:funder_id>/identifiers/<slug:reference_slug>/<uuid:object_id>/',
        FunderIdentifierEditView.as_view(),
        name='funder_identifiers_edit',
    ),
    path(
        'metadata/funders/<uuid:funder_id>/identifiers/<slug:reference_slug>/<uuid:object_id>/remove/',
        FunderIdentifierRemoveView.as_view(),
        name='funder_identifiers_remove',
    ),

    path('metadata/reference/<slug:reference_slug>/', ReferenceListView.as_view(), name='metadata_reference_list'),
    path('metadata/reference/<slug:reference_slug>/<str:object_id>/', ReferenceEditView.as_view(), name='metadata_reference_edit'),
    path('metadata/reference/<slug:reference_slug>/<str:object_id>/delete/', ReferenceDeleteView.as_view(), name='metadata_reference_delete'),
]
