# Generated by Django 5.0.12 on 2025-10-30 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acl_agent_uri',
            field=models.URLField(blank=True, help_text='URI used when matching foaf:Person ACL rules.', max_length=1024, null=True, verbose_name='ACL agent URI'),
        ),
        migrations.CreateModel(
            name='GroupACL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acl_agent_uri', models.URLField(blank=True, help_text='URI used when matching foaf:Group ACL rules.', max_length=1024, null=True, verbose_name='ACL agent URI')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acl_profile', to='auth.group')),
            ],
            options={
                'verbose_name': 'Group ACL profile',
                'verbose_name_plural': 'Group ACL profiles',
            },
        ),
    ]
