# Generated by Django 5.0.12 on 2025-11-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_acl_agent_uri_groupacl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saml_persistent_id',
            field=models.CharField(blank=True, help_text='Immutable identifier supplied by the Identity Provider for returning SAML users.', max_length=255, null=True, unique=True, verbose_name='SAML persistent identifier'),
        ),
    ]
