# Generated by Django 5.0.12 on 2026-01-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_populate_acl_agent_uris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupacl',
            name='acl_agent_uri',
            field=models.CharField(blank=True, help_text='URI used when matching foaf:Group ACL rules (e.g., urn:lacos:group:groupname).', max_length=1024, null=True, verbose_name='ACL agent URI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='acl_agent_uri',
            field=models.CharField(blank=True, help_text='URI used when matching foaf:Person ACL rules (e.g., urn:lacos:user:username).', max_length=1024, null=True, verbose_name='ACL agent URI'),
        ),
    ]
