# Generated by Django 5.2.12 on 2026-04-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_create_collection_manager_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamlCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SAML country',
                'verbose_name_plural': 'SAML countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SamlIdp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=2048, unique=True)),
                ('display_name', models.CharField(max_length=512)),
                ('logo', models.URLField(blank=True, max_length=2048)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idps', to='users.samlcountry')),
            ],
            options={
                'verbose_name': 'SAML identity provider',
                'verbose_name_plural': 'SAML identity providers',
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['display_name'], name='users_samli_display_92aa96_idx'), models.Index(fields=['country'], name='users_samli_country_384fd6_idx')],
            },
        ),
    ]
