# Generated by Django 5.2.12 on 2026-04-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_saml_discovery_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samlidp',
            name='entity_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='samlidp',
            name='logo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
